### ISSUE TITLE
FrozenExpression 

### ISSUE THREAD

**Issue by charishma13** [SymbolicML/DynamicExpressions.jl#100]
Hello MilesCranmer,

I'm Charishma Puli from [ATOMS lab](https://atomslab.github.io/members/) under supervision of [Dr. Tyler R. Josephson](https://cbee.umbc.edu/josephson/). I would like to bring to your attention an issue we are currently facing. Firstly, I wanted to remind about our project focused on freezing a part of the expression to identify acid-base reactions involving zeolites in chemistry. 

We're implementing your proposed idea of creating a FrozenExpression by defining Metadata and other functions to freeze the nodes. We started with exploring AbstractExpression, ParametricExpression and StructuredExpression Julia codes. We then want to test how the metadata of the a AbstractExpressionNode looks like. However, we encountered an error when trying to import the get_metadata function from DynamicExpressions.jl.

**Here is the import code I used:**
`using DynamicExpressions: AbstractExpressionNode, get_metadata`
**Error:**
`ERROR: LoadError: UndefVarError: get_metadata not defined`

I can successfully import other functions and structures from different modules, such as AbstractExpressionNode, string_tree and eval_diff_tree_array using DynamicExpressions. However, this issue seems specific to the expression.jl module. I'm uncertain why DynamicExpressions.jl is not recognizing the reexports from expression.jl. Could this be related to the constructors? I would greatly appreciate your assistance in navigating this error. Thank you

**Note:** 
In addition, prior to this error, I faced another issue in the PatchMethodsModule will executing import code using DynamicExpressions. I resolved it by modifying the code as follows:

```
#using DynamicExpressions: get_contents, with_contents
using ..ExpressionModule: Expression, get_tree, get_operators, get_contents, with_contents
```

**Comment by MilesCranmer** [comment]
Hi @charishma13,
Is this still an issue or did you manage to solve it?
Thanks,
Miles

**Comment by charishma13** [comment]
Hello @MilesCranmer,

Yes, the issue is resolved. I tried running the Julia program in the same folder as DynamicExpression.jl.

Thank you, Charishma Puli
