### ISSUE TITLE
what's special about variable name `operators`?

### ISSUE THREAD

**Issue by Moelf** [SymbolicML/DynamicExpressions.jl#21]
in all the examples we define a variable `operators` but don't use it explicitly, can we document it or make an explicit API?

**Comment by MilesCranmer** [comment]
(The variable name `operators` does not matter, by the way - calling `OperatorEnum()` is what sets up the default behavior of the evaluation methods, if you're using this convenience API)

**Comment by MilesCranmer** [comment]
This is the code in question: https://github.com/SymbolicML/DynamicExpressions.jl/blob/7835abfbeefd93fe18ae53befe63b1470de99ade/src/OperatorEnumConstruction.jl#L9-L31
